{
 "title": "01 Schema Registry - Overview",
 "tags": [ "schema-registry" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"schema-registry\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"schema-registry\", cluster_id=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Schemas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Schema Registry Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"})"
    }
   ]
  },
  {
   "title": "Schema registered over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(schema_type) (kafka_schema_registry_schemas_created{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Schemas created",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(schema_type)(kafka_schema_registry_schemas_created{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(schema_type)(kafka_schema_registry_schemas_deleted{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"})",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count{cluster_id=~\".*\", cluster_type=\"schema-registry\"})"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jetty_metrics_connections_active{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_rate{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests latency 99p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_latency_99{cluster_id=\"$cluster\", cluster_type=\"schema-registry\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}