{
 "title": "02 - Controllers (KRaft)",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"kafka\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lead Controller Commit Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_raft_metrics_commit_latency_avg{cluster_id=~\"$cluster\"} >=0 ) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lead Controller Commit Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_raft_metrics_commit_latency_max{cluster_id=~\"$cluster\"} >=0 ) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Append Rate (Leader)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_raft_metrics_append_records_rate{cluster_id=~\"$cluster\", instance=~\".+\"} > 0) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Fetch Rate (Followers & Observers)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_raft_metrics_fetch_records_rate{cluster_id=~\"$cluster\", instance=~\".+\"} > 0) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft IO Thread - Idle Ratio",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_raft_metrics_poll_idle_ratio_avg{cluster_id=~\"$cluster\", instance=~\".+\"}) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(kafka_server_raft_metrics_current_state{cluster_id=~\"$cluster\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))"
    },
    {
     "expr": "(kafka_server_raft_metrics_log_end_offset{cluster_id=~\"$cluster\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kafka_server_raft_metrics_high_watermark{cluster_id=~\"$cluster\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kafka_server_raft_metrics_log_end_epoch{cluster_id=~\"$cluster\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kafka_server_raft_metrics_current_epoch{cluster_id=~\"$cluster\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(kafka_server_raft_metrics_current_vote{cluster_id=~\"$cluster\"} + on (cluster_id, instance) group_left(node_id) (0 * kafka_server_app_info_version))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}