{
 "title": "07 - Kafka Cluster - Controller (raft)",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Online Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_app_info_version{})"
    }
   ]
  },
  {
   "title": "Online Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",})"
    }
   ]
  },
  {
   "title": "Online Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{name=\"LeaderCount\",})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",})"
    }
   ]
  },
  {
   "title": "Quorum Leader (node_id)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics{name=\"current-leader\",})"
    }
   ]
  },
  {
   "title": "Voted Leader (node_id)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics{name=\"current-vote\",})"
    }
   ]
  },
  {
   "title": "High Water Mark",
   "type": "stat",
   "description": "The high watermark maintained on this member",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics{name=\"high-watermark\",})"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current quorum epoch.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_server_raft_metrics{name=\"current-epoch\",})"
    }
   ]
  },
  {
   "title": "Fetch Records Rate",
   "type": "timeseries",
   "description": "The average number of records fetched from the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(job)(kafka_server_raft_metrics{name=\"fetch-records-rate\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Records Rate",
   "type": "timeseries",
   "description": "The average number of records appended per sec by the leader of the raft quorum.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(job)(kafka_server_raft_metrics{name=\"append-records-rate\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_raft_metrics{name=\"current-state\",})"
    },
    {
     "expr": "kafka_server_app_info_version{}"
    },
    {
     "expr": "kafka_server_raft_metrics{name=\"current-state\",}"
    }
   ]
  },
  {
   "title": "High Watermark",
   "type": "timeseries",
   "description": "The high watermark maintained on this member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max without(job, instance)(kafka_server_raft_metrics{name=\"high-watermark\",})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "description": "The current quorum epoch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max without(job, instance)(kafka_server_raft_metrics{name=\"current-epoch\",})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}