{
 "title": "Streams StateStore (put/fetch)",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "put-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition_id,task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"put-rate\", job=\"analytics\"})",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "put-rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum without(partition_id,thread_id,instance,job,task_id) (kafka_streams_stream_state_metrics{metric=\"put-rate\", job=\"analytics\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "fetch-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition_id,task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"fetch-rate\", job=\"analytics\"})",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "fetch-rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum without(partition_id,thread_id,instance,job,task_id) (kafka_streams_stream_state_metrics{metric=\"fetch-rate\", job=\"analytics\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "remove-rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition_id,task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"remove-rate\", job=\"analytics\"})",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "remove-rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum without(partition_id,thread_id,instance,job,task_id) (kafka_streams_stream_state_metrics{metric=\"remove-rate\", job=\"analytics\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "estimage-num-keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition_id,task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"estimate-num-keys\", job=\"analytics\"})",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "estimate-num-rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum without(partition_id,thread_id,instance,job,task_id) (kafka_streams_stream_state_metrics{metric=\"estimate-num-keys\", job=\"analytics\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  }
 ]
}