{
 "title": "Streams Processes",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "kafka_streams_stream_thread_metrics_task_created_total"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "kafka_streams_stream_thread_metrics_poll_rate{job=~\"$job\"}"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "kafka_streams_stream_thread_metrics_task_created_total{instance=~\"${instance}\"}"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "kafka_streams_stream_processor_node_metrics_process_total{instance=~\"${instance}\",thread_id=~\"${thread}\"}"
    }
   },
   {
    "name": "process",
    "label": "process",
    "query": {
     "query": "kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{task_id=~\"$task\",thread_id=~\"${thread}\",instance=~\"$instance\",job=~\"$job\"}\n"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "kafka_streams_stream_task_metrics_process_rate{instance=~\"${instance}\",thread_id=~\"${thread}\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "e2e latency (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(partition_id) ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", job=~\"${job}\"}) >=0)",
     "legendFormat": "{{thread_id}}/{{task_id}}/{{processor_node_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg  ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}) >=0)",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without(partition_id) ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_min{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", job=~\"${job}\"}) >= 0)",
     "legendFormat": "{{thread_id}}/{{task_id}}/{{processor_node_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (min)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg  ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_min{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}) >=0)",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max without(partition_id) ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_max{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", job=\"${job}\"}) >= 0)",
     "legendFormat": "{{thread_id}}//{{task_id}}/{{processor_node_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (max)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg  ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_max{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}) >=0)",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}