{
 "title": "01 - Flink - Overview",
 "description": "Apache Flink",
 "tags": [ "flink" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster_type=\"flink\"}, cluster_id)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "# of TaskManagers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "{{instance}} jobmanager运行的job数量"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  {
   "title": "BackPressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "inPoolUsag",
     "type": "graph",
     "description": "inPoolUsag",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inPoolUsage{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inPoolUse"
      }
     ]
    },
    {
     "title": "outPoolUsage",
     "type": "graph",
     "description": "outPoolUsage",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outPoolUsage{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outPoolUsage"
      }
     ]
    },
    {
     "title": "outputQueueLength",
     "type": "graph",
     "description": "outputQueueLength",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outputQueueLength{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outputQueueLength"
      }
     ]
    },
    {
     "title": "numRecordsOutPerSecond",
     "type": "graph",
     "description": "numRecordsOutPerSecond",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsOutPerSecond"
      }
     ]
    },
    {
     "title": "numRecordsInPerSecond",
     "type": "graph",
     "description": "umRecordsInPerSecond",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsInPerSecond"
      }
     ]
    },
    {
     "title": "inputQueueLength",
     "type": "graph",
     "description": "inputQueueLength",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inputQueueLength{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inputQueueLength"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TaskManager Garbage Collection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc count"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Count[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc count"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_年轻代gc时间"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[30s])",
     "legendFormat": "{{host}}_{{tm_id}}_老年代gc时间"
    }
   ]
  },
  {
   "title": "live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} jobManager live Thread counts"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} taskManger live Thread counts"
    }
   ]
  },
  {
   "title": "connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "offset commit failures to Kafka",
   "type": "graph",
   "description": "offset commit failures to Kafka",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_commitsFailed{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "records has dropped due to arriving late.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numLateRecordsDropped{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "job-downtime",
   "type": "graph",
   "description": "job-downtime",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_downtime{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_downtime"
    }
   ]
  },
  {
   "title": "rocksdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "delayed write rate",
     "type": "graph",
     "description": "delayed write rate",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_actual_delayed_write_rate{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
      }
     ]
    },
    {
     "title": " entries in the unflushed immutable memtables",
     "type": "graph",
     "description": "entries in the unflushed immutable memtables.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_deletes_imm_mem_tables{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}} delete entries"
      },
      {
       "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_entries_imm_mem_tables{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}} total entries"
      }
     ]
    },
    {
     "title": "background errors in RocksDB",
     "type": "graph",
     "description": "background errors in RocksDB",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_background_errors{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
      }
     ]
    },
    {
     "title": "unreleased snapshots",
     "type": "graph",
     "description": "unreleased snapshots",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_snapshots{job_name=~\"$job_name\"}",
       "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
      }
     ]
    }
   ]
  }
 ]
}