{
 "title": "02 - Flink - Kafka",
 "description": "Flink - Kafka",
 "tags": [ "flink" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster_type=\"flink\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KafkaSource (Consumer) - message (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{cluster_id=~\"$cluster\"}, \"source\", \"$1\", \"operator_name\", \"Source:_?([^_]*)_?([^_]*)_?(.*)\")) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "KafkaSink (Producer) - message (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaProducer_record_send_rate{cluster_id=~\"$cluster\"}, \"sink\", \"$1 $2 $3\", \"operator_name\", \"Sink:_?([^_]*)_?([^_]*)_?(.*)\")) by (sink)",
     "legendFormat": "out {{sink}}"
    }
   ]
  },
  {
   "title": "KafkaSource (Consumer) - byte (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_incoming_byte_rate{cluster_id=~\"$cluster\"}, \"source\", \"$1\", \"task_name\", \"Source:_?([^_]*)_?([^_]*)_?(.*)\")) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "KafkaSink (Producer) - byte (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(label_replace(flink_taskmanager_job_task_operator_KafkaProducer_outgoing_byte_rate{cluster_id=~\"$cluster\"}, \"sink\", \"$1 $2 $3\", \"operator_name\", \"Sink:_?([^_]*)_?([^_]*)_?(.*)\")) by (sink)",
     "legendFormat": "out {{sink}}"
    }
   ]
  }
 ]
}