{
 "title": "03 - Flink - IO",
 "description": "Apache Flink",
 "tags": [ "flink" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster_type=\"flink\"}, cluster_id)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "JobManager Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max-flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "JobManager NonHeap Memory Available",
   "type": "graph",
   "description": "JobManager NonHeap Memory Available",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed-flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager Memory Available",
   "type": "timeseries",
   "description": "TaskManager Memory Available",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max-flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "TaskManger NonHeap Memory Available",
   "type": "timeseries",
   "description": "TaskManger NonHeap Memory Available",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed-flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  }
 ]
}