{
 "title": "04 - Flink - System",
 "description": "Apache Flink",
 "tags": [ "flink" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster_type=\"flink\"}, cluster_id)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "jobmanager network  Rate per second",
   "type": "graph",
   "description": "jobmanager network Rate per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_Network_bond0_ReceiveRate",
     "legendFormat": "{{host}} ReceiveRate"
    },
    {
     "expr": "flink_jobmanager_System_Network_bond0_SendRate",
     "legendFormat": "{{host}} SendRate"
    }
   ]
  },
  {
   "title": "TaskManager network Rate per second",
   "type": "graph",
   "description": "TaskManager network Rate per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_Network_bond0_ReceiveRate",
     "legendFormat": "{{host}}_{{tm_id}} ReceiveRate"
    },
    {
     "expr": "flink_taskmanager_System_Network_bond0_SendRate",
     "legendFormat": "{{host}}_{{tm_id}} SendRate"
    }
   ]
  },
  {
   "title": "JobManager CPU USE",
   "type": "graph",
   "description": "JobManager CPU USE",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_CPU_Usage",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager CPU USE",
   "type": "graph",
   "description": "TaskManager CPU USE",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_CPU_Usage",
     "legendFormat": "{{host}}_{{tm_id}}"
    }
   ]
  }
 ]
}