{
 "title": "05 - Flink - Checkpoint",
 "description": "Apache Flink",
 "tags": [ "flink" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster_type=\"flink\"}, cluster_id)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Checkpoint duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job=\"$job\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job=\"$job\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints{job=\"$job\"}",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "last duration" }
   ],
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{job=\"$job\"})",
     "legendFormat": "duration"
    },
    {
     "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints{job=\"$job\"}",
     "legendFormat": "in progress"
    }
   ]
  },
  {
   "title": "lastCheckpointDuration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{host}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "Last CheckPoint Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_lastCheckpointSize{cluster_id=~\"$cluster\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "numberOfFailedCheckpoints",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{cluster_id=~\"$cluster\"}[2m])",
     "legendFormat": "{{host}}_{{job_name}}_FailedCheckpoints"
    }
   ]
  }
 ]
}