{
 "title": "06 - Flink - Job",
 "description": "Apache Flink",
 "tags": [ "flink" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster_type=\"flink\"}, cluster_id)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "inPoolUsag",
   "type": "timeseries",
   "description": "inPoolUsag",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "outPoolUsage",
   "type": "graph",
   "description": "outPoolUsage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outPoolUsage{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outPoolUsage"
    }
   ]
  },
  {
   "title": "outputQueueLength",
   "type": "graph",
   "description": "outputQueueLength",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_outputQueueLength{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_outputQueueLength"
    }
   ]
  },
  {
   "title": "numRecordsOutPerSecond",
   "type": "graph",
   "description": "numRecordsOutPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsOutPerSecond"
    }
   ]
  },
  {
   "title": "numRecordsInPerSecond",
   "type": "graph",
   "description": "umRecordsInPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_RecordsInPerSecond"
    }
   ]
  },
  {
   "title": "inputQueueLength",
   "type": "graph",
   "description": "inputQueueLength",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_inputQueueLength{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inputQueueLength"
    }
   ]
  }
 ]
}