{
 "title": "Druid - Overview",
 "tags": [ "druid" ],
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Druid Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "druid_health_status" }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"RUNNING\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Sucess Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"FAILED\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Druid Task's Sucess Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\"}) / count(druid_tasks_duration{}) * 100"
    }
   ]
  },
  {
   "title": "Total Datasources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(druid_datasource{})" }
   ]
  },
  {
   "title": "Total Segments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(druid_segment_count)" }
   ]
  },
  {
   "title": "Unloaded Segments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_emitted_metrics{metric_name=\"segment-loadQueue-count\"}))"
    }
   ]
  },
  {
   "title": "Unloaded Segments Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_emitted_metrics{metric_name=\"segment-loadQueue-size\"})"
    }
   ]
  }
 ]
}