{
 "title": "Kafka Connect Cluster - Worker",
 "description": "Kafka Connect",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=\"$cluster_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connect Worker",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_app_info{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\",start_time_ms!=\"\"}"
    },
    {
     "expr": "kafka_connect_app_info{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\",version!=\"\"}"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_count{job=\"kafka-connect\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_startup_success_total{job=\"kafka-connect\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_startup_failure_total{job=\"kafka-connect\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_count{job=\"kafka-connect\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_startup_success_total{job=\"kafka-connect\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_startup_failure_total{job=\"kafka-connect\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connection_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_failed_authentication_total{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Success authentication connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_successful_authentication_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Average number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_request_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_response_rate{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  }
 ]
}