{
 "title": "Kafka Connect Cluster - Connector",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=\"$cluster_id\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", cluster_id=~\"connect-cluster\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_metrics{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",connector_type!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_metrics{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_total_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"})"
    },
    {
     "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_info{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    }
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_avg{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_max{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio{job=\"kafka-connect\", instance=~\"$instance\",cluster_id=~\"connect-cluster\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}